# type: ignore

# calcluates EOS and absorption for forsterite
# fully in SI units

import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(precision=4)

from contourpy import contour_generator
from scipy.interpolate import RegularGridInterpolator, CubicSpline, interp1d

import sys
import os

sys.path.append(f'{os.getcwd()}/aneos-forsterite-2019-1.0.0')
import eostable

# loads the eos table from file
NewEOS = eostable.extEOStable()  # FIRST make new empty EOS object

# LOAD EXTENDED 301 SESAME FILE GENERATED BY STSM VERSION OF ANEOS
NewEOS.loadextsesame('aneos-forsterite-2019-1.0.0/NEW-SESAME-EXT.TXT')
# LOAD STANDARD 301 SESAME FILE GENERATED BY STSM VERSION OF ANEOS
NewEOS.loadstdsesame('aneos-forsterite-2019-1.0.0/NEW-SESAME-STD.TXT')

NewEOS.MODELNAME = 'Forsterite-ANEOS-SLVTv1.0G1'  # string set above in user input
NewEOS.MDQ = np.zeros((NewEOS.NT, NewEOS.ND))  # makes the empty MDQ array

# EOS properties
NewEOS.MATID = 1.0
NewEOS.DATE = 190802
NewEOS.VERSION = 0.1
NewEOS.FMN, NewEOS.FMW = 70., 140.691
NewEOS.R0REF, NewEOS.K0REF = 3.22, 1.1E12
NewEOS.T0REF, NewEOS.P0REF = 298., 1.E6

NewEOS.loadaneos(aneosinfname='aneos-forsterite-2019-1.0.0/ANEOS.INPUT',
                aneosoutfname='aneos-forsterite-2019-1.0.0/ANEOS.OUTPUT', silent=True)

# change units to SI
NewEOS.rho = NewEOS.rho * 1e3
NewEOS.P, NewEOS.S = NewEOS.P * 1e9, NewEOS.S * 1e6
NewEOS.U = NewEOS.U * 1e6
NewEOS.cs = NewEOS.cs * 1e2
NewEOS.vc.Sl, NewEOS.vc.Sv = NewEOS.vc.Sl * 1e6, NewEOS.vc.Sv * 1e6
NewEOS.vc.Pl, NewEOS.vc.Pv = NewEOS.vc.Pl * 1e9, NewEOS.vc.Pv * 1e9
NewEOS.vc.rl, NewEOS.vc.rv = NewEOS.vc.rl * 1e3, NewEOS.vc.rv * 1e3
NewEOS.vc.Uv = NewEOS.vc.Uv * 1e6

P_critical_point, S_critical_point = NewEOS.cp.P * 1e9, NewEOS.cp.S * 1e6

P_interp = RegularGridInterpolator((NewEOS.rho, NewEOS.T), NewEOS.P.T, method='linear', bounds_error=False, fill_value=None)
S_interp = RegularGridInterpolator((NewEOS.rho, NewEOS.T), NewEOS.S.T, method='linear', bounds_error=False, fill_value=None)

rho_vc_v_interp = CubicSpline(NewEOS.vc.Pv[::-1], NewEOS.vc.rv[::-1], extrapolate=False)
T_vc_v_interp = CubicSpline(NewEOS.vc.Pv[::-1], NewEOS.vc.T[::-1], extrapolate=False)
S_vc_v_interp = CubicSpline(NewEOS.vc.Pv[::-1], NewEOS.vc.Sv[::-1], extrapolate=False)
U_vc_v_interp = CubicSpline(NewEOS.vc.Pv[::-1], NewEOS.vc.Uv[::-1], extrapolate=False)

S_vc = np.concatenate([[0], np.flip(NewEOS.vc.Sl), NewEOS.vc.Sv])
P_vc = np.concatenate([[1e-7], np.flip(NewEOS.vc.Pl), NewEOS.vc.Pv])
P_vapor_curve = interp1d(S_vc, P_vc, bounds_error=False, fill_value=np.nan)

def make_into_pair_array(arr1, arr2):
    arr1, arr2 = np.nan_to_num(arr1), np.nan_to_num(arr2)

    if type(arr1) is np.ndarray and type(arr2) is np.ndarray:

        if arr1.ndim == 0:
            return np.array([arr1[()], arr2[0]])
        if arr2.ndim == 0:
            return np.array([arr1[0], arr2[()]])

        try:
            assert np.all(arr1.shape == arr2.shape)
        except AssertionError:
            print(f'arr1 = {arr1} \n arr1 shape = {arr1.shape}')
            print(f'arr2 = {arr2} \n arr2 shape = {arr2.shape}')
            assert np.all(arr1.shape == arr2.shape)

        assert arr1.ndim == 1 or arr1.ndim == 2

        arr = np.array([arr1, arr2])

        if arr1.ndim == 1:
            return np.transpose(arr, axes=(1, 0))
        elif arr1.ndim == 2:
            return np.transpose(arr, axes=(1, 2, 0))

    else:

        if type(arr1) is np.ndarray:
            if arr1.ndim == 1:
                arr1 = arr1[0]

        if type(arr2) is np.ndarray:
            if arr2.ndim == 1:
                arr2 = arr2[0]

        return np.array([arr1, arr2])

P_EOS = lambda rho, T: P_interp(make_into_pair_array(rho, T))
S_EOS = lambda rho, T: S_interp(make_into_pair_array(rho, T))

isentrope_generator = contour_generator(NewEOS.rho, NewEOS.T, NewEOS.S)
isobar_generator = contour_generator(NewEOS.rho, NewEOS.T, NewEOS.P)

def make_isentrope(s):

    isentrope = isentrope_generator.lines(s)[0]

    rho_isentrope = isentrope[:, 0]
    T_isentrope = isentrope[:, 1]

    P_isentrope = P_EOS(rho_isentrope, T_isentrope)

    rho_interpolator = CubicSpline(P_isentrope, rho_isentrope)
    T_interpolator = CubicSpline(P_isentrope, T_isentrope)

    return rho_interpolator, T_interpolator

def vapor_curve(P):
    return rho_vc_v_interp(P), T_vc_v_interp(P), S_vc_v_interp(P), U_vc_v_interp(P)

def phase(P, s):
    min_P = 1e-5  # pressures below this are invalid

    result = np.zeros_like(P)
    result = np.where(P <= min_P, 0, result)
    result = np.where(np.logical_and(P < P_vapor_curve(s), P > min_P), 2, result)
    result = np.where(np.logical_and(P >= P_vapor_curve(s), s < S_critical_point), 1, result)
    result = np.where(np.logical_and(P >= P_vapor_curve(s), s >= S_critical_point), 3, result)
    result = np.where(np.logical_and(result == 3, P >= P_critical_point), 4, result)

    return result


# calculates the absorption of the vapor
def alpha_v(rho, T):
    B0 = 6e17  # m^-1
    B1, B2 = 37, -11.6
    rho_n, T_n = 1900, 4150  # kg/m^3, K
    r, t = rho / rho_n, T / T_n

    result = B0 * (r ** (1 / 3)) * t * np.exp(-B1 / t) * np.exp(-B2 * (r / t))

    return np.nan_to_num(result)
